/*
 * WaitDialog.java
 *
 * Created on October 30, 2001, 11:23 AM
 */

package com.xsb.xj;

import javax.swing.*;
//import com.xsb.xj.*;

/**
 *
 * @author  tanya
 */
@SuppressWarnings("serial")
public class WaitDialog extends javax.swing.JDialog implements Runnable{

    private PrologAction prologAction;
    
    /** Creates new form waitDialig */
    public WaitDialog(PrologAction prologAction) {
        super();
        initComponents();
        this.setLocation((int)(getToolkit().getScreenSize().getWidth()-this.getSize().getWidth())/2,
                                (int)(getToolkit().getScreenSize().getHeight()-this.getSize().getHeight())/2);
        this.prologAction = prologAction;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/com/xsb/xj/images/ani-gear.gif"))
        );
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);
        
        jLabel2.setText("                                       Please wait                                 ");
        getContentPane().add(jLabel2, java.awt.BorderLayout.NORTH);
        
        pack();
    }//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
/*        setVisible(false);
        dispose();*/
    }//GEN-LAST:event_closeDialog

    public void run() {
        setVisible(true);
	validate();
        if(this.prologAction != null){
           this.prologAction.setThreaded(true);
           this.prologAction.setInAWTThread(false);
           this.prologAction.doit();
        }
        /*while(!this.prologAction.actionConcluded()){
	  }*/
	this.prologAction.waitUntilEnd();
        setVisible(false);
	dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
