/*
 * XJPasswordDialog.java
 *
 * Created on June 10, 2005, 4:18 PM
 */

package com.xsb.xj;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author  crojo
 *A simple prompt to acquire User Name and Password information from a user.
 */
@SuppressWarnings("serial")
public class XJPasswordDialog extends javax.swing.JDialog {

    private boolean okClicked;
    
    /** Creates new form XJPasswordDialog */
    public XJPasswordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        okClicked = false;
        initComponents();
        userNameField.setText("");
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        
        //centerizing the window
        Point screenCenter = new Point((int)d.getWidth()/2-(int)this.getWidth()/2,
                (int)d.getHeight()/2-(int)this.getHeight()/2 );
        this.setLocation(screenCenter);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        userNameAndPasswordPanel = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        userNameField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Please Log In");
        setName("loginPrompt");
        userNameAndPasswordPanel.setLayout(new java.awt.GridBagLayout());

        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        userNameAndPasswordPanel.add(passwordField, gridBagConstraints);

        userNameField.setText("WWWWWWWWWWWWWWWWWWWWWW");
        userNameField.setMinimumSize(new java.awt.Dimension(80, 20));
        userNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameFieldKeyPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        userNameAndPasswordPanel.add(userNameField, gridBagConstraints);

        userNameLabel.setText("User Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        userNameAndPasswordPanel.add(userNameLabel, gridBagConstraints);

        passwordLabel.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        userNameAndPasswordPanel.add(passwordLabel, gridBagConstraints);

        getContentPane().add(userNameAndPasswordPanel, java.awt.BorderLayout.CENTER);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void userNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameFieldKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            setOkClicked(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_userNameFieldKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            setOkClicked(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setOkClicked(false);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setOkClicked(true);
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    public boolean isOkClicked() {
        return okClicked;
    }
    
    public void show(boolean b){
        this.okClicked = false;
        super.setVisible(b);
    }

    public void setOkClicked(boolean okClicked) {
        this.okClicked = okClicked;
    }

    public char[] getPasswordAsCharArray() {
        return passwordField.getPassword();
    }

    public void setPasswordField(javax.swing.JPasswordField passwordField) 
    {
        this.passwordField = passwordField;
    }

    public String getUserName() {
        return userNameField.getText();
    }

    public void setUserNameField(javax.swing.JTextField userNameField) {
        this.userNameField = userNameField;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel userNameAndPasswordPanel;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
    
}
